manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: etlcpp
      url-base: https://github.com/ETLCPP

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
    - name: etl
      remote: etlcpp
      revision: 20.48.0
      path: modules/lib/etl
